spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to AlexBank cards related prod APIs "
  contactDetails:
    name: "Simon Peterson - Product Owner"
    email: "peterson@alexbank.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721