pring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to AlexBank loans related QA APIs "
  contactDetails:
    name: "Susan Martina - QA Lead"
    email: "martina@alexbank.com"
  onCallSupport:
    - (785) 545-6565
    - (853) 546-3467