
  build:
    version: "3.0"
accounts:
  message: "Welcome to AlexBank accounts related local APIs "
  contactDetails:
    name: "Joseph Dutson - Developer"
    email: "dutson@alexbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345