

build:
  version: "2.0"

accounts:
  message: "Welcome to AlexBank accounts related QA APIs "
  contactDetails:
    name: "Susan Ray - QA Lead"
    email: "susanray@alexbank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371