
build:
  version: "1.0"

cards:
  message: "Welcome to AlexBank cards related production APIs "
  contactDetails:
    name: "Simon Peterson - Product Owner"
    email: "peterson@alexbank.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721
