
build:
  version: "1.0"

loans:
  message: "Welcome to AlexBank loans related production APIs "
  contactDetails:
    name: "Paul Sidorov - Product Owner"
    email: "sidorov@eazybank.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956
