
build:
  version: "3.0"

loans:
  message: "Welcome to AlexBank loans related local APIs "
  contactDetails:
    name: "Greg Tonia - Developer"
    email: "tonia@alexbank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934